// Auto generated by utensor-cli

#ifndef __SOURCE_TRAINED_H
#define __SOURCE_TRAINED_H
#include "uTensor/core/context.hpp"
void get_trained_ctx(Context& ctx, Tensor* input_0);
#endif // __SOURCE_TRAINED_H